services:
  db:
    image: postgres:latest
    container_name: angoway_postgres
    restart: always
    environment:
      POSTGRES_USER: angoway
      POSTGRES_PASSWORD: root
      POSTGRES_DB: angowaydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - angoway-network

  angowayappbackend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: angoway_backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://angoway:root@db:5432/angowaydb
    ports:
      - "3300:3300"
    depends_on:
      - db
    networks:
      - angoway-network

networks:
  angoway-network:
    driver: bridge

volumes:
  postgres_data:
