services:
  angowayappbackend:
    image: angowayappbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3300:3300
  angowaydatabase:
    image: angowaydatabase
    build:
      context: .
      dockerfile: ./Dockerfile.database
    environment:
      DATABASE_PASSWORD: root
      DATABASE_NAME: angowaydb
    ports:
      - 3306:3306