networks:
  angoway-network:
    driver: bridge

services:
  angowaydatabase:
    image: postgres:15-alpine
    container_name: angowaydatabase
    restart: always
    environment:
      POSTGRES_USER: angoway
      POSTGRES_PASSWORD: root
      POSTGRES_DB: angowaydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      - test: ['CMD', 'pg_isready']
      - interval: 10s
      - timeout: 5s
      - retries: 5
    networks:
      - angoway-network

  angowayappbackend:
    build:
      context: .
      dockerfile: Dockerfile
    image: angowayappbackend
    container_name: angowayappbackend
    depends_on:
      - angowaydatabase
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://angoway:root@angowaydatabase:5432/angowaydb
      PORT: 3300
    ports:
      - '3300:3300'
    networks:
      - angoway-network

volumes:
  postgres_data:
